### ISSUE TITLE
All cursive words are the same

### ISSUE THREAD

**Issue by VOID404** [BentonEdmondson/knock#10]
I used `knock` (bundled release) to unpack my `acsm` but in the resulting `epub` all cursive words (`<i>`) got replaced by the first word that appeared in cursive. I am not sure if `knock` is at fault, but I have no idea how to even debug this...

**Comment by BentonEdmondson** [comment]
If you have a Windows or macOS machine available, your best bet is check if the issue happens using the official method. i.e. download [ADE](https://www.adobe.com/solutions/ebook/digital-editions/download.html) and open the ebook through there to see if it also has the issue

**Comment by VOID404** [comment]
I bought the book on `eBooks.com`. It displays correctly in the web viewer. I do not have access to windows nor macOS

**Comment by VOID404** [comment]
Is there anything else I could do for the purpose of debugging? Keep in mind I am not using latest `knock`, because of the release thingy...

**Comment by BentonEdmondson** [comment]
Also do you mean italics? Are you saying the correct sentence is

> _In the metaphysics of identity, the ship of Theseus is a thought experiment that..._

and is being displayed as

> _In In In In In, In In In In In In In In In..._

?

**Comment by VOID404** [comment]
> Are you using the latest release? I'm not sure I understand what you're saying

What I am saying is I am not using the latest version. I am using 0.1.0-alpha (af4f8b2) bundled version.

I actually failed at running ADE with wine before I found you program (which is btw amazing. Great job <3 )
I can try displaying the eBook on mobile maybe? Adobe supports mobile, right?

> I could open it in ADE on my Windows machine but you'd have trust me with your user/pass

I can set some temporary one, do you have a private communicator?

**Comment by VOID404** [comment]
> Also do you mean italics? Are you saying the correct sentence is

I am reading _The Hitchhiker's Guide to the Galaxy_. The first word that appeared in italics was _bulldozer_

> The word _bulldozer_ wandered through his mind for a moment in search of something to connect with.

And now everytime anything is supposed to be in italics, it just says _bulldozer_
So for example in original:
> ‘But look, you found the notice, didn’t you?’
‘Yes,’ said Arthur, ‘yes I did. It was on display in the bottom of a locked ﬁling cabinet stuck in a disused lavatory with a sign on the door saying _Beware of the Leopard_.’

and in my version:

> ‘But look, you found the notice, didn’t you?’
‘Yes,’ said Arthur, ‘yes I did. It was on display in the bottom of a locked ﬁling cabinet stuck in a disused lavatory with a sign on the door saying _bulldozer_.’

**Comment by BentonEdmondson** [comment]
> I can try displaying the eBook on mobile maybe? Adobe supports mobile, right?

Ah, good idea! Try this for now. Another thought is maybe your epub reader is causing the problem? Try [unzipping](https://gist.github.com/jamesktan/5977349562e6f6cab9ea) it and opening it as a plaintext file to see if the text itself contains this bug

**Comment by VOID404** [comment]
> maybe your epub reader is causing the problem?

I tried my boox reader and calibre reader, and also viewing the html in calibre editor

**Comment by VOID404** [comment]
The problem persists in ADE on Android!

So I guess this is not an issue with this repo... I guess that counts as solved?

Sorry for bothering ya and thx for your help

**Comment by BentonEdmondson** [comment]
Wow that's disappointing, I think eBooks.com takes returns. That must've been really weird to read through at first. Yeah I assume that the encrypted EPUB file sent over by Adobe has the flaw so there's no feasible way for this project to fix it, only option is to complain to Adobe over phone/email. No worries opening this and feel free to reopen if you find a good solution

**Comment by VOID404** [comment]
FYI, I fixed the first chapter by hand and when I reach the next one I'll check if it's corrupted too
If it is, then chapter by chapter I'll fix it ¯\\\_(ツ)\_/¯

I paid for this book and I am reading it in it's original form, whether the DRM wants me to or not :P
