### ISSUE TITLE
Cant export adobe***.der key

### ISSUE THREAD

**Issue by sp8996** [BentonEdmondson/knock#12]
How to export .der keys from Knock so that I can make DRM free PDFs using calibre dedrm tools?
Knock generates a .drm file for pdf .acsm files , renaming .drm .pdf doesnt help , it asks for a password....it will be easy to remove the drm if we can export the adobe.der key somehow...In libgourou , there was an option to export private key into .der file.

**Comment by BentonEdmondson** [comment]
Right now I'm focused on adding ACSM to PDF support (https://github.com/BentonEdmondson/knock/issues/3) and AAX to M4B support (https://github.com/BentonEdmondson/knock/issues/9) so I won't be adding this functionality anytime soon
