### ISSUE TITLE
Changing the email used

### ISSUE THREAD

**Issue by Sapechi** [BentonEdmondson/knock#14]
Hello. I downloaded the release version knock-0.1.0-alpha-x86_64-linux and got it running on my manjaro setup, no issues there. Now I am wondering, where does the program store the email/password used by the program and how do I change the email used?
I started by trying to use my schools email with the program. I entered the email/pass from school but that didn't work, the program errors with "invalid password" message. It might be because the university has made the accounts and it uses the 'workplace login' thing. I can login to adobes site with that email.
I made a trash login to adobe like the readme suggests. That works, the program runs with that now and can do it's thing. It fails to deDRM the books, it just downloads a <filename>.drm file that seems to be a .pdf that has a password that I don't know. I think it uses a decryption that can't be removed?
Now I'm wondering, how do I change the email I used when I first tried the program, the 'trash login' with adobe? Where is this stored and can it be changed?

PS: sorry if my english is poor, hopefully not too bad that the message isn't understood. I'm not a native English speaker

**Comment by BentonEdmondson** [comment]
Hi. The ACSM data is currently stored in `$XDG_CONFIG_HOME/knock`, which is usually `~/.config/knock`. To try a different email, delete the folder.

I will add a CLI flag to forcefully reset the config. For future reference, I am planning to move the config to move ACSM config data to `$XDG_CONFIG_HOME/knock/acsm`. This is because I am adding AAX support, and that config will go in `$XDG_CONFIG_HOME/knock/aax`.

Regarding PDFs, see

**Comment by Sapechi** [comment]
A force flag sounds good for resetting, deleting the files works for now. 
Thank you for the reply. And big thank you for making this program. It's much appreciated :)

**Comment by BentonEdmondson** [comment]
No problem, hopefully it's working well for you. I'm gonna leave this open until I get the force flag implemented

**Comment by BentonEdmondson** [comment]
With `1.2.0` release logins are anonymous; i.e. no email is ever entered, so this is fixed
