### ISSUE TITLE
E_ADEPT_REQUEST_EXPIRED 

### ISSUE THREAD

**Issue by andersorder** [BentonEdmondson/knock#15]
Hi and thank you for writing this. I get the following error when running the script:
ERROR: 
CompletedProcess(args=['adept-download', '-d', '/home/xwande/.config/knock/device.xml', '-a', '/home/xwande/.config/knock/activation.xml', '-k', '/home/xwande/.config/knock/devicesalt', '-o', '/home/xwande/Downloads/TomSlater_2021_ShakingUptheCityIgnoranceInequalityandth.drm', '-f', '/home/xwande/Downloads/TomSlater_2021_ShakingUptheCityIgnoranceInequalityandth.acsm'], returncode=0, stdout=b'Exception code : 0x1003\nMessage        : E_ADEPT_REQUEST_EXPIRED http://rps2images.ebscohost.com/fulfillment/Fulfill 2021-10-06T17:19:23-04:00%20(1633555163000)%20is%20before%202021-10-08T07:58:26-04:00%20(1633694306795)\n\n', stderr=b'')
What did I do wrong? I am on Debian bulls-eye 64bit

**Comment by BentonEdmondson** [comment]
How much time was there between when you bought the book and when you ran the script?

**Comment by BentonEdmondson** [comment]
Feel free to reopen if problem persists

**Comment by BentonEdmondson** [comment]
Feel free to reopen if problem persists

**Comment by AndyJWard** [comment]
Hi Benton,
I had the E_ADEPT.. message too - I had downloaded the .acsm the previous day.  I downloaded a fresh copy and all worked perfectly - many, many thanks!!

**Comment by andersorder** [comment]
It worked fo me with a fresh file as well. Thank you.

**Comment by andersorder** [comment]
It worked fo me with a fresh file as well. Thank you.
