### ISSUE TITLE
Wishlist: Decrypt using computer key instead of email

### ISSUE THREAD

**Issue by hackerb9** [BentonEdmondson/knock#16]
Hi! Knock looks swell, but I don't want an account with Adobe and it would be nice if Knock didn't require one.

Adobe Digital Editions itself does not require an account. One can use the acsm file to download a version encrypted for a specific machine with ADE. The encrypted version is then decryptable by the I ♥ Cabbages DeDRM plugin in Calibre.

I do not know what level of wizardly skill is needed for this, but my hope is that someday the humble Knock Spell will acquire the power to decrypt an acsm file without an account and at last free me from the fetters of Wine and ADE. 

Thanks!

**Comment by Leseratte10** [comment]
I don't want to advertise for a "competing product", but you could try my [ACSM Input Plugin](https://github.com/Leseratte10/acsm-calibre-plugin) for Calibre. This plugin does support anonymous authorizations without an AdobeID, and it allows you to just add ACSM files to Calibre like any other book (and have it magically turn into an EPUB or PDF).

Given that "knock" is only a wrapper around libgourou, that functionality (anonymous auth) would need to be added to libgourou first before knock can support / use it.

**Comment by hackerb9** [comment]
> I don't want to advertise for a "competing product"

There are no competitors here, only friends. 😀

**Comment by BentonEdmondson** [comment]
With `1.2.0`, emails are not required anymore (logins are anonymous)
