### ISSUE TITLE
Symbol lookup error: /usr/lib/libc.so.6: undefined symbol: _dl_fatal_printf

### ISSUE THREAD

**Issue by jackrgm** [BentonEdmondson/knock#17]
Running `./knock /path/to/book.acsm` gives me the following error:

`./nix/store/j0rfffzsih095w4nvl6cp0zbmdiaycfs-nix-user-chroot-2c52b5f/bin/nix-user-chroot: symbol lookup error: /usr/lib/libc.so.6: undefined symbol: _dl_fatal_printf, version GLIBC_PRIVATE`

Using Arch Linux, latest release of Knock, and followed the README.

**Comment by BentonEdmondson** [comment]
Did you try this solution from the readme?:
> If you receive an error that says something like ./nix/store/...: not found or ./nix/store/...: No such file or directory then you might not have user namespaces enabled. Try running the following to fix it:
> ```
> echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf
> sudo reboot
> ```

**Comment by BentonEdmondson** [comment]
Feel free to reopen if the issue persists

**Comment by BentonEdmondson** [comment]
Fixed for sure in release `1.2.0`
