### ISSUE TITLE
Running knock hangs

### ISSUE THREAD

**Issue by hackerb9** [BentonEdmondson/knock#18]
When I manually run `adept-register -u libralibre@sharklasers.com`, it tells me that I have "fully signed and device activated" in the .adept directory. 

When I run `knock`, it tells me "This device is not registered" and has me put in the email address and password. After that it prints "Registering this device with Adobe..." and then just freezes forever. Hitting ^C gives a python backtrace for line 33 (subprocess.run of "adept-register -u email -O adobe_dir") which implies to me that the -O option is not working. 

```
This device is not registered with Adobe.
Enter your Adobe account's email address: libralibre@sharklasers.com
Enter your Adobe account's password: 
Registering this device with Adobe...

^CTraceback (most recent call last):
  File "./knock", line 33, in <module>
    result = subprocess.run([
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1981, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
```

I found a workaround, which is to not use Knock to do the registration:
```bash
adept-register -u libralibre@sharklasers.com
mv .adept ~/.config/knock
```

**Comment by BentonEdmondson** [comment]
This is an issue with [libgourou](http://indefero.soutade.fr/p/libgourou/). In the next release of knock, the CLI output will more clearly display the output of dependencies that knock calls. This will give better debug info for issues like this. Until then, try registering the device in `.adept`, and then reregister with the `-O` option and see what the output is when it hangs. Then [report the issue to the libgourou developer](http://indefero.soutade.fr/p/libgourou/issues/).

**Comment by hackerb9** [comment]
I am not sure this is a bug in libgourou as the libgourou utilities work to register an account. It is only knock that fails.
