### ISSUE TITLE
ERROR: /media/hdd/Downloads/book.acsm does not exist.

### ISSUE THREAD

**Issue by zd4y** [BentonEdmondson/knock#19]
I am getting this error: `ERROR: /media/hdd/Downloads/book.acsm does not exist.` when I use knock with a file in `/media/hdd` which is the mount point of a second drive I have.

The command I am using is: `knock /media/hdd/Downloads/book.acsm`

Moving the file `book.acsm` to `$HOME` and using `knock ~/book.acsm` works as expected, no error

**Comment by Linux-Geezer** [comment]
I'm having a similar issue, although my ACSM file is under ~/downloads. I also temporarily enabled user namespaces, but that didn't help. I also tried moving the ACSM file under my home folder but that didn't work either.

Just a rant: Why can really nice ebook DRM removal apps be created for Windows and macOS (www.ebook-converter.com), but not for Linux?

**Comment by hackerb9** [comment]
> I'm having a similar issue under Debian Unstable, although my ACSM file is under ~/downloads. I also temporarily enabled user namespaces, but that didn't help. I also tried moving the ACSM file under my home folder but that didn't work either.

I'm using Debian and knock works for me. But, I compiled it myself and there were some hiccups in the process (which I've reported here: [libgourou #1](https://github.com/BentonEdmondson/libgourou-utils/issues/1), [libgourou #2](https://github.com/BentonEdmondson/libgourou-utils/issues/2), [libgourou #3](https://github.com/BentonEdmondson/libgourou-utils/issues/3), #18)
 
> Just a rant: Why can really nice ebook DRM removal apps be created for Windows and macOS ([www.ebook-converter.com](http://www.ebook-converter.com)), but not for Linux? I'd pay for such an app.

Just a guess here, but I think it's because many of the people who have chosen Free Software are aware of the problems with DRM and avoid it like the plague. Personally, I do not want to encourage publishers who think that DRM is harmless, so I do not buy books with DRM. If I didn't have friends and family who get trapped by formats like ACSM, I would not have spent any time trying to find workarounds for the latest DRM schemes. As it is, I've wasted too much of my life on DRM and I have no energy left to write an app to make it more convenient. That's one of the reasons I'm thankful for @BentonEdmondson for packaging up libgourou with a nice little script.

By the way, `knock`_is_ really nice once you get it working. But, if you do not like command line programs, you can always get the [Calibre DeACSM plugin](https://github.com/Leseratte10/acsm-calibre-plugin/releases). Either way, if you feel like paying money to someone, consider Grégory Soutadé, the author of [libgourou](http://indefero.soutade.fr/p/libgourou/)  which does all the hard work behind the scenes.

**Comment by zd4y** [comment]
After finally getting nix working in my system I compiled this myself and now I don't have that error, though I am still having problems unrelated to this issue.

Should I close this issue now or maybe leave it open as a remainder to create a new release?

**Comment by BentonEdmondson** [comment]
@zd4y:
> I am getting this error: ERROR: /media/hdd/Downloads/book.acsm does not exist. when I use knock with a file in /media/hdd which is the mount point of a second drive I have.

The next release of knock completely refactors the checks for file existence, readability, etc. I suspect that will solve this issue.

> Well now that I entered my email and password using knock ~/book.acsm it says ERROR: No internet access but I guess that's a different issue

The next release will give much clearer debugging information on errors like this (this error is a [libgourou](http://indefero.soutade.fr/p/libgourou/) error). Until then it's hard to say what's going on.

> After finally getting nix working in my system I compiled this myself and now I don't have that error, though I am still having problems unrelated to this issue.

Alright so it looks like the issue was with [nix-bundle](https://github.com/matthewbauer/nix-bundle) (the builder to make it runnable on a non-Nix system). For now I won't try to resolve it.

> Should I close this issue now or maybe leave it open as a remainder to create a new release?

Let's wait until @Linux-Geezer's issue is resolved.

---

@Linux-Geezer:

> I'm having a similar issue under Debian Unstable, although my ACSM file is under ~/downloads.

See what I wrote above about the next release. Once that comes out I think it will resolve the issue. Until then please post the output error.

**Comment by Linux-Geezer** [comment]
It's the same output error as the OP provided, except for the fact that my file is under the ~/downloads folder.

**Comment by Linux-Geezer** [comment]
> I'm using Debian and knock works for me. But, I compiled it myself and there were some hiccups in the process (which I've reported here: [libgourou #1](https://github.com/BentonEdmondson/libgourou-utils/issues/1), [libgourou #2](https://github.com/BentonEdmondson/libgourou-utils/issues/2), [libgourou #3](https://github.com/BentonEdmondson/libgourou-utils/issues/3), #18)
>

I'm not interested in compiling something that is supposed to work as is. The non-Nix version is supposed to work under any 64-bit Linux distro.
 
> Just a guess here, but I think it's because many of the people who have chosen Free Software are aware of the problems with DRM and avoid it like the plague. Personally, I do not want to encourage publishers who think that DRM is harmless, so I do not buy books with DRM. If I didn't have friends and family who get trapped by formats like ACSM, I would not have spent any time trying to find workarounds for the latest DRM schemes. As it is, I've wasted too much of my life on DRM and I have no energy left to write an app to make it more convenient. That's one of the reasons I'm thankful for @BentonEdmondson for packaging up libgourou with a nice little script.
>

It's very difficult to avoid DRM ebooks if you desire the ebook format and I do desire the format. The apps on ebook-converter.com always worked for me under Windows. Unfortunately, if my memory serves me well, I was unable to get the apps to work under Wine.
 
> By the way, `knock`_is_ really nice once you get it working. But, if you do not like command line programs, you can always get the [Calibre DeACSM plugin](https://github.com/Leseratte10/acsm-calibre-plugin/releases). Either way, if you feel like paying money to someone, consider Grégory Soutadé, the author of [libgourou](http://indefero.soutade.fr/p/libgourou/) which does all the hard work behind the scenes.

I don't mind using the command line. However, Knock will only remove Adobe DRM, not the other DRM formats that one may encounter; e.g. Kindle. I've tried using DeDRM in the past and at the time of my attempt, I was unsuccessful at getting it to work. Getting DeDRM to work is also a bit cumbersome in my opinion. So basically, the aforementioned issues were the reason for my rant.

**Comment by BentonEdmondson** [comment]
@Linux-Geezer 

> It's the same output error as the OP provided, except for the fact that my file is under the ~/downloads folder.

Alright we'll see if the next release fixes it.

> Knock will only remove Adobe DRM, not the other DRM formats that one may encounter; e.g. Kindle.

This is true, but I want to support more formats in the future. In the next release I'm adding ACSM to PDF and AAX to M4B support. Please open issues for other formats you want supported.

**Comment by Linux-Geezer** [comment]
@BentonEdmondson 

Okay, I'll wait for the next release. ETA? Thank you for the info about opening an issue to ask for more formats.

**Comment by BentonEdmondson** [comment]
@Linux-Geezer as long as https://github.com/BentonEdmondson/knock/issues/3#issuecomment-962699178 works I'll have it out this weekend

**Comment by BentonEdmondson** [comment]
Try this on the latest release and see what happens

**Comment by TheTurtleHat** [comment]
I still experience the error, initially after a delay.
`Error: Invalid value for 'PATH': File 'boox.acsm' does not exist.`

**Comment by zd4y** [comment]
Same here, there was also a delay the first time I tried and after moving the file to my home folder it works:
```
➜ ~ ls .local/bin/knock*
.local/bin/knock-0.1.0-alpha-x86_64-linux  .local/bin/knock-1.0.0-alpha-x86_64-linux
➜ ~ echo $DOWNLOAD
/media/hdd/Downloads
➜ ~ knock-0.1.0-alpha-x86_64-linux $DOWNLOAD/book.acsm 
ERROR: /media/hdd/Downloads/book.acsm does not exist.
➜ ~ knock-1.0.0-alpha-x86_64-linux $DOWNLOAD/book.acsm 
Usage: .knock-wrapped [OPTIONS] PATH
Try '.knock-wrapped --help' for help.

Error: Invalid value for 'PATH': File '/media/hdd/Downloads/book.acsm' does not exist.
➜ ~ mv $DOWNLOAD/book.acsm .
➜ ~ knock-1.0.0-alpha-x86_64-linux ~/book.acsm
Received an ACSM (Adobe) file...
This device is not registered with Adobe.
Enter your Adobe account's email address: MY-EMAIL
Enter your Adobe account's password: 
Registering this device with Adobe...

knock> adept_activate -u MY-EMAIL -O /home/alejandro/.config/knock/acsm

Enter password for <MY-EMAIL> : 
MY-EMAIL fully signed and device activated in /home/alejandro/.config/knock/acsm

knock[0]>

Downloading the book from Adobe...

knock> acsmdownloader -d /home/alejandro/.config/knock/acsm/device.xml -a /home/alejandro/.config/knock/acsm/activation.xml -k /home/alejandro/.config/knock/acsm/devicesalt -o /home/alejandro/book.drm -f /home/alejandro/book.acsm

Created /home/alejandro/book.drm

knock[0]>

Decrypting the file...

knock> rmdrm-epub /home/alejandro/.config/knock/acsm/activation.xml /home/alejandro/book.drm /home/alejandro/book.epub

Successfully decrypted book.drm as book.epub

knock[0]>

DRM-free EPUB file created:
/home/alejandro/book.epub
```

**Comment by zd4y** [comment]
> Try this on the latest release (1.1.0-alpha) and see what happens

I tried with 1.0.0-alpha, I don't see the 1.1.0-alpha in releases

**Comment by zd4y** [comment]
I was able to reproduce the issue in the same disk
1. Shrink a partition and create a new ext4 primary partition with gparted live usb
2. Mount the partition, move the file to that partition and run knock:
```
➜ ~ sudo mount /dev/nvme0n1p9 /mnt
[sudo] password for alejandro: 
➜ ~ sudo mv ~/book.acsm /mnt
➜ ~ knock-1.0.0-alpha-x86_64-linux /mnt/book.acsm 
Usage: .knock-wrapped [OPTIONS] PATH
Try '.knock-wrapped --help' for help.

Error: Invalid value for 'PATH': File '/mnt/book.acsm' does not exist.
```
My root partition is btrfs and I thought that maybe the different filesystem mattered so I formatted /dev/nvme0n1p9 as btrfs but same error

**Comment by TheTurtleHat** [comment]
I can avoid the issue (and hit authentication problems) by moving the book file from my BTRFS home directory into /tmp/.

**Comment by Linux-Geezer** [comment]
Still doesn't work...sigh...


<code>$ bin/knock/knock downloads/ebooks_drm/xyz--ebook.acsm</code>
<code>Usage: .knock-wrapped [OPTIONS] PATH</code>
<code>Try '.knock-wrapped --help' for help.</code.>

<code>Error: Invalid value for 'PATH': File 'downloads/ebooks_drm/xyz--ebook.acsm' does not exist.</code>

**Comment by BentonEdmondson** [comment]
@zd4y, @Linux-Geezer, @TheTurtleHat try release `1.2.0`, it should fix all these issues.

**Comment by TheTurtleHat** [comment]
I tried the new version and it worked like a charm

**Comment by BentonEdmondson** [comment]
Awesome!
