### ISSUE TITLE
Add option for reproducible output EPUBs

### ISSUE THREAD

**Issue by Pieter1024** [BentonEdmondson/knock#20]
If I run knock twice on the same ACSM file, I get two EPUBs with different file hashes. The differences between the files are specific enough that they could be used as a means of fingerprinting the associated Adobe ID.

The solution is to normalize the output EPUB. If you unpack and then repack the EPUB, you strip away the differences between different instances of the same e-book. If you build the new EPUB deterministically, you can even compare hashes between EPUBs to check that no fingerprinting information remains.

I created a script that does this: https://github.com/Pieter1024/clean-epub. However, I think it would be convenient to provide this functionality as an optional post-processing step in knock. Unfortunately, as I don't run NixOS, I can't implement it myself.

**Comment by BentonEdmondson** [comment]
This is very interesting. Thanks for writing this up.

When you compare the EPUBs after unzipping them, is the only difference between them the timestamps of the files or are there other differences?

**Comment by Pieter1024** [comment]
I've had two users of the same ebook platform buy the same book. They then each ran their ACSMs through knock, using their respective Adobe IDs. I compared the resulting EPUBs.

When I run diffoscope on the EPUBs from knock, the only difference between the EPUBs is the order of the files in the zip. The timestamps for the files in the zip are exactly the same, and they're all set to the same value, from a few years ago. I guess that the timestamps of the zip contents are fixed when the ebook is created.

When I first unzip the EPUBs to separate directories and then run diffoscope on the two directories, the only difference is the modification times of the subdirectories. The modification times for the files in the directories are the same as they were in the zip. The modification times for the subdirectories are set to the moment I unzipped the EPUBs. I guess that the subdirectories are not actually part of the zip contents, and are created on the fly.

**Comment by hackerb9** [comment]
> I created a script that does this: https://github.com/Pieter1024/clean-epub. However, I think it would be convenient to provide this functionality as an optional post-processing step in knock. Unfortunately, as I don't run NixOS, I can't implement it myself.

I've been informed that this repository is only for Nix. I think it would be more generally useful if, instead of getting your tool included in Knock, to have it added upstream to libgourou. That way, any wrapper based on libgourou would have the option of creating reproducible EPUBs. 

That is fascinating that the zipfile order is being permuted. It is hard to imagine a reason that would happen _other_ than fingerprinting an EPUB. Thank you for taking the time to figure that out!

**Comment by Pieter1024** [comment]
I'm not familiar with the project goals of libgourou. I agree that if it's within their scope, including it there is the most general solution to the problem.

However, I don't want the perfect to be the enemy of the good. A knock-only implementation would be a great start. After, we can start the conversation with libgourou, to see whether they want to provide the functionality as well.

If @BentonEdmondson indicates that this is indeed not in scope for the knock project (other than implementing the functionality when libgourou provides it), I will happily go over to libgourou and propose they include it.

**Comment by BentonEdmondson** [comment]
@hackerb9

> I've been informed that this repository is only for Nix.

This is false. Knock's readme clearly states how to install Knock on non-Nix systems. I don't know who you think informed you of this. Please read through the readme before making another comment.

@Pieter1024

This is in scope for Knock. I am planning to implement it.

**Comment by BentonEdmondson** [comment]
Out of scope. I think it's good to clean the epubs but another tool should be used as Knock is just to get the Adobe file purely. Another option to clean the epubs is to convert them to latex with [pandoc](https://github.com/jgm/pandoc).
