### ISSUE TITLE
Wishlist: Create DRM-free Kindle Formatted eBooks

### ISSUE THREAD

**Issue by Linux-Geezer** [BentonEdmondson/knock#21]
It would be nice to be able to create DRM-free Kindle formatted eBooks.

**Comment by mendhak** [comment]
I think this is where [Calibre](https://calibre-ebook.com/) would be better suited, isn't it?  See:  https://www.cnet.com/news/the-best-e-reader-for-2021/

It can be automated too, when adding an .epub to Calibre, you can get it to convert the book for your Kindle device.

**Comment by Linux-Geezer** [comment]
Calibre by itself does not remove DRM from eBooks, which would include most Kindle formatted ebooks unless they are DRM-free. You need to use a plugin from DeDRM under Calibre to remove DRM. I tried using the DeDRM plugin with Calibre a few months ago and I couldn't get it to work. I may try again, but my plate is full with other projects right now.

**Comment by hackerb9** [comment]
> You need to use a plugin from DeDRM under Calibre to remove DRM

DeDRM is a real pain if you're not using Microsoft Windows. The reason is that Adobe Digital Editions encrypts the epub using a bunch of Microsoft Windows specific hardware info. Just take a look at [adobekey.py](https://github.com/apprenticeharper/DeDRM_tools/blob/73af5d355d17ca487d939272c248f2ea0e522396/DeDRM_plugin/adobekey.py#L347). That's why I was excited to find out about Knock which uses libgourou instead. 

There is another Calibre plugin, one that is based on a rewrite of libgourou to Python, called [acsm-calibre-plugin](https://github.com/Leseratte10/acsm-calibre-plugin). I have not had a reason to try it yet, but I expect it would work easily, unlike DeDRM.

**Comment by BentonEdmondson** [comment]
@Linux-Geezer what is the file extension for Kindle ebooks?

**Comment by Linux-Geezer** [comment]
> @Linux-Geezer what is the file extension for Kindle ebooks?

For Kindle 8 format, the extension is azw. For Kindle 10 format, the successor to Kindle 8, the extension is kfx. I don't know if existing *.azw books were automatically switched over when the Kindle 10 format came out.

Note that there will be more than one *.kfx file in the associated ebook folder. The largest file should be the actual ebook. I don't know what the other *.kfx files are used for.

[https://fileinfo.com/extension/kfx](url)

**Comment by hackerb9** [comment]
There's also Amazon's  .kcr format, but I don't think that's cracked yet.

**Comment by Linux-Geezer** [comment]
> There's also Amazon's .kcr format, but I don't think that's cracked yet.

Cracking shouldn't be required. The way I understand how DeDRM works, all you need to do is use the DRM key, at least on an Android device with developer mode enabled.

**Comment by Leseratte10** [comment]
Well, that is correct, but Amazon is very very quick to roll out a new version of their DRM once people figure out how that works, so you need a bunch of workarounds (like using an ancient version of Kindle4PC) to get Amazon books with the old DRM version that can still be removed.

**Comment by hackerb9** [comment]
Yes, also kcr (Kindle Cloud Reader) format is "online only", which means a library (like libgourou for acsm) that can talk to the Amazon server and download the book is necessary.

**Comment by Linux-Geezer** [comment]
> Well, that is correct, but Amazon is very very quick to roll out a new version of their DRM once people figure out how that works, so you need a bunch of workarounds (like using an ancient version of Kindle4PC) to get Amazon books with the old DRM version that can still be removed.

Whoever codes the software available at ebook-converter.com doesn't seem to have a problem keeping on top of the changes. I never had a problem converting Kindle books using that software.

**Comment by Linux-Geezer** [comment]
> Yes, also kcr (Kindle Cloud Reader) format is "online only", which means a library (like libgourou for acsm) that can talk to the Amazon server and download the book is necessary.

There's a way around that, although it would be very time consuming. Take screenshots, convert screenshots to PDF using GIMP. I've done it with another vendor's online reader, although only a few pages.

**Comment by Leseratte10** [comment]
> Whoever codes the software available at ebook-converter.com doesn't seem to have a problem keeping on top of the changes.

That software uses the same code as any other DRM removal. They also have instructions telling you to downgrade the Kindle software to an old version: https://ebook-converter.com/219-kfx-ebook-drm-remove-fail.htm and https://ebook-converter.com/222-drmexception-invalid-file-format.htm

**Comment by hackerb9** [comment]
> > Yes, also kcr (Kindle Cloud Reader) format is "online only", which means a library (like libgourou for acsm) that can talk to the Amazon server and download the book is necessary.
> 
> There's a way around that, although it would be very time consuming. Take screenshots, convert screenshots to PDF using GIMP. I've done it with another vendor's online reader, although only a few pages.

Perhaps we are getting off-topic, since I doubt `knock` will ever implement such a method, however, to save yourself time in the future, you can use ImageMagick to convert a directory of images into a PDF. I typically use `ocrmypdf` after that to do optical character recognition (it's actually just a simple frontend to `tesseract`). 

```bash
$ convert Screenshot*.png concatenated.pdf
$ ocrmypdf  --title "Man and Land in the Far-East" --author "Pierre Gourou" concatenated.pdf book.pdf
```

You could also do it as a pipeline:
```
img2pdf  --pagesize A4  page *.png  |  ocrmypdf  -  myfile.pdf
```

**Comment by derek-mba** [comment]
> Calibre by itself does not remove DRM from eBooks, which would include most Kindle formatted ebooks unless they are DRM-free. 

So you don't want to _create_ Kindle formatted books, you want to _decrypt_ Kindle formatted books. atm, `knock` on an ACSM for an EPUB and then Calibre to convert it to an AZW file seems the way to go.
