### ISSUE TITLE
Unable to create /home/name/Descargas/isabel.drm

### ISSUE THREAD

**Issue by nondeve** [BentonEdmondson/knock#22]
I got this error, would you mind help me, please?

root@user:/home/name/Descargas# ./knock /home/name/Descargas/isabel.acsm 
Downloading the EPUB file from Adobe...
ERROR: 
CompletedProcess(args=['adept-download', '-d', '/root/.config/knock/device.xml', '-a', '/root/.config/knock/activation.xml', '-k', '/root/.config/knock/devicesalt', '-o', '/home/name/Descargas/isabel.drm', '-f', '/home/name/Descargas/isabel.acsm'], returncode=0, stdout=b'Exception code : 0x1004\nMessage        : Unable to create /home/name/Descargas/isabel.drm\n\n', stderr=b'')

**Comment by BentonEdmondson** [comment]
In that directory, run `ls -l ..` and post the output.

**Comment by nondeve** [comment]
drwxrwxr-x  2 name name   4096 nov  8  2017 Biblioteca de calibre
drwxrwxr-x  6 name name   4096 feb  2  2020 Calibre Library
drwxrwxr-x  8 name name 167936 nov 18 00:59 Descargas
drwxr-xr-x 36 name name   4096 nov  9 17:16 Documentos
drwxr-xr-x  2 name name   4096 sep  4  2017 Escritorio
drwxrwxr-x 10 name name  12288 nov 15 17:47 Imágenes
drwxrwxr-x  5 name name   4096 nov  9 17:17 Música
drwxr-xr-x  2 name name   4096 sep  4  2017 Plantillas
drwxr-xr-x  2 name name   4096 sep  4  2017 Público
drwxr-xr-x 10 name name   4096 nov  9 16:09 Vídeos

**Comment by nondeve** [comment]
> In that directory, run `ls -l ..` and post the output.

drwxrwxr-x 2 name name 4096 nov 8 2017 Biblioteca de calibre
drwxrwxr-x 6 name name 4096 feb 2 2020 Calibre Library
drwxrwxr-x 8 name name 167936 nov 18 00:59 Descargas
drwxr-xr-x 36 name name 4096 nov 9 17:16 Documentos
drwxr-xr-x 2 name name 4096 sep 4 2017 Escritorio
drwxrwxr-x 10 name name 12288 nov 15 17:47 Imágenes
drwxrwxr-x 5 name name 4096 nov 9 17:17 Música
drwxr-xr-x 2 name name 4096 sep 4 2017 Plantillas
drwxr-xr-x 2 name name 4096 sep 4 2017 Público
drwxr-xr-x 10 name name 4096 nov 9 16:09 Vídeos

**Comment by fluxus-collab** [comment]
Hello @BentonEdmondson ,

I have quite the same situation.
Once it worked, the next one not.
I have this error now:

````
   ~/Documents  ./knock /home/fluxus/Documents/URL.acsm                                                                                                                                                                            ✔ 
Downloading the EPUB file from Adobe...
ERROR: 
CompletedProcess(args=['adept-download', '-d', '/home/fluxus/.config/knock/device.xml', '-a', '/home/fluxus/.config/knock/activation.xml', '-k', '/home/fluxus/.config/knock/devicesalt', '-o', '/home/fluxus/Documents/URL.drm', '-f', '/home/fluxus/Documents/URL.acsm'], returncode=0, stdout=b'Exception code : 0x1003\nMessage        : E_ADEPT_REQUEST_EXPIRED http://acs4.kobo.com/fulfillment/Fulfill 2021-11-30T11:12:18-05:00%20(1638288738000)%20is%20before%202021-12-01T10:51:45-05:00%20(1638373905120)\n\n', `stderr=b'')

````


````
    ~/Documents  ls -l ..                                                                                                                                                                                                         1 ✘ 
total 27748
drwxr-xr-x 1 fluxus fluxus      132 30 nov 10:50 'Bibliothèque calibre'
drwxr-xr-x 1 fluxus fluxus      894  1 déc 11:22  Bureau
drwxr-xr-x 1 fluxus fluxus       44 29 nov 19:23  CiscoSpark
drwxr-xr-x 1 fluxus fluxus      206  1 déc 16:51  Documents
drwxr-xr-x 1 fluxus fluxus        0 19 oct 10:03  Downloads
-rw-r----- 1 fluxus fluxus    16219 19 nov 13:02  hp-check.log
-rw-r----- 1 fluxus fluxus  1842759  6 oct 18:51  hpscan001.png
drwxr-xr-x 1 fluxus fluxus      406 29 nov 13:41  Images
-rw-r--r-- 1 fluxus fluxus 26551100  5 oct 19:49  krita-2057-document_0-autosave.kra
drwxr-xr-x 1 fluxus fluxus        0 27 sep 22:49  Modèles
drwxr-xr-x 1 fluxus fluxus      572  9 oct 15:12  Musique
drwxr-xr-x 1 fluxus fluxus        0 27 sep 22:49  Public
drwxr-xr-x 1 fluxus fluxus      124 21 nov 10:50  Recettes
drwx------ 1 fluxus fluxus       32  2 oct 15:30  snap
drwxr-xr-x 1 fluxus fluxus     8352  1 déc 16:50  Téléchargements
drwxr-xr-x 1 fluxus fluxus      346 14 nov 11:25  Vidéos
drwxr-xr-x 1 fluxus fluxus       16  1 déc 11:31 'VirtualBox VMs'
drwxr-xr-x 1 fluxus fluxus      216  1 déc 16:09  Zotero
````

Waiting for a clue, I can read the first book at least.

Thank you for helping me not to reinstall Windows just for that.

Have a good time.

**Comment by BentonEdmondson** [comment]
Please try this on the latest release (1.1.0-alpha) and see what happens

**Comment by nondeve** [comment]
> 

I got this error:

Downloading the book from Adobe...

knock> acsmdownloader -d /root/.config/knock/acsm/device.xml -a /root/.config/knock/acsm/activation.xml -k /root/.config/knock/acsm/devicesalt -o /home/name/Descargas/isabel.drm -f /home/name/Descargas/isabel.acsm

Exception code : 0x1004
Message        : Unable to create /home/name/Descargas/isabel.drm


knock[1]>

Error: Command returned error code 1.

**Comment by fluxus-collab** [comment]
> Please try this on the latest release (1.1.0-alpha) and see what happens

Thank you.

It goes further. Now it logs in. But I receive this error.

````
   ~/Documents  ./knock /home/fluxus/Documents/URL.acsm                                                                                                                                                                  1 ✘  58s  
Received an ACSM (Adobe) file...
Downloading the book from Adobe...

knock> acsmdownloader -d /home/fluxus/.config/knock/acsm/device.xml -a /home/fluxus/.config/knock/acsm/activation.xml -k /home/fluxus/.config/knock/acsm/devicesalt -o /home/fluxus/Documents/URL.drm -f /home/fluxus/Documents/URL.acsm

Exception code : 0x1003
Message        : E_ADEPT_REQUEST_EXPIRED http://acs4.kobo.com/fulfillment/Fulfill 2021-11-30T11:12:18-05:00%20(1638288738000)%20is%20before%202021-12-05T04:27:48-05:00%20(1638696468403)


knock[1]>

Error: Command returned error code 1.

**Comment by BentonEdmondson** [comment]
@nondeve that is an error coming from a dependency. I'll open an issue in the dependency when I get a chance.

@fluxus-collab I suspect that means you bought the ACSM so long ago that the file can no longer be redeemed.

**Comment by fluxus-collab** [comment]
Thank you for you answer. The file was bought a few days ago. :)

**Comment by BentonEdmondson** [comment]
@nondeve retry on release `1.2.0`

**Comment by nondeve** [comment]
> @nondeve retry on release `1.2.0`

Hi, Benton. I just tried with a file and I must say it worked perfectly. Infinite thanks for this, seriously. God bless you.

**Comment by BentonEdmondson** [comment]
Awesome! Glad it worked
