### ISSUE TITLE
Long Passwords not accepted

### ISSUE THREAD

**Issue by TheSiege** [BentonEdmondson/knock#23]
Hi,
I tried using knock with a 100 character long password (default of my password manager) and got this error:
Enter your Adobe account's email address: ****
Enter your Adobe account's password: 
Registering this device with Adobe...
ERROR: 
CompletedProcess(args=['adept-register', '-u', '****', '-O', '/home/****/.config/knock'], returncode=0, stdout=b'Exception code : 0x5004\nMessage        : error:0406D06E:rsa routines:RSA_padding_add_PKCS1_type_2:data too large for key size\n\n', stderr=b'')

(I anonymized personal data with ****)

login into the adobe account via web works fine

**Comment by BentonEdmondson** [comment]
I think that the Adobe servers are returning these errors so there's nothing I can do to fix it. I guess you'll just have to use a shorter password. Reopen if you have any other ideas.
