### ISSUE TITLE
'adept-register' issue

### ISSUE THREAD

**Issue by mzuer** [BentonEdmondson/knock#24]
Thank for this tool ... however I get the following issue

FileNotFoundError: [Errno 2] No such file or directory: 'adept-register'

any idea how I can solve it ? thanks in advance

**Comment by BentonEdmondson** [comment]
Based on the error, I'm guessing you simply `git clone`d the repo and tried running the script. This won't work.

If you are on NixOS, you need to install via the Nix flake.

If you aren't on NixOS, download the latest [release](https://github.com/BentonEdmondson/knock/releases) and follow the instructions in the readme.
