### ISSUE TITLE
Registration works, but download fails with "ERROR: No internet access"

### ISSUE THREAD

**Issue by tlavoie** [BentonEdmondson/knock#25]
Greetings. I am running the full install file on the current NixOS stable release, which I believe doesn't support flakes yet. (Note: I'm very new to Nix in general, learning as I go.)

The registration step worked fine, but the download of the encrypted EPUB fails with:

Downloading the EPUB file from Adobe...
ERROR: No internet access

I would like to diagnose what the adept-download program is doing, but everything gets tidied up after the program closes. If there is a way to install without the flake (or with?) on NixOS stable, that might help figure out what's going on.

Cheers!

**Comment by BentonEdmondson** [comment]
> I would like to diagnose what the adept-download program is doing, but everything gets tidied up after the program closes.

I'll have an update out this weekend that makes the subprocess errors transparent. This will make this easier to diagnose.

**Comment by tlavoie** [comment]
Awesome, thanks!

Semi-related, any tips on getting flakes configured correctly would be great, perhaps an example config. I upgraded nix to use the flake feature, but hadn't quite got it working just yet. As a workaround though, this did the trick:

nix shell github:BentonEdmondson/knock --command knock ./URLLink.acsm

(Might be a useful tip for others.)

**Comment by BentonEdmondson** [comment]
Try out 1.1.0-alpha, it will give more debug information.

Regarding your NixOS question specifically, the readme has a snippet of what your flake should look like to install knock:

```nix
{
    inputs.knock.url = "github:BentonEdmondson/knock";
    outputs = { self, knock }: { /* knock.defaultPackage.x86_64-linux is the package */ };
}
```

Additionally, you can take a look at my personal [configuration](https://github.com/BentonEdmondson/nixos-config), which installs knock.

For non-declarative installs, you can run `nix profile install github:BentonEdmondson/knock`, but I recommend putting it directly in your configuration instead of doing this. Feel free to send me any more questions/issues you have regarding NixOS.

**Comment by tlavoie** [comment]
Thanks Benton. Trying 1.1.0-alpha release download, it is failing with:

Exception code : 0x500a
Message        : Error SSL handshake failed

Additionally, I note that the alpha release seems to expect a full path to the .acsm file. For now, I have tried the non-declarative version above, and it works fine, relative path included.

I appreciate having your overall config to crib from, though admit I need to invest some time to understand the relevant syntax details. Don't want to be blindly cargo-culting anything. I do like how you've got things broken out per system and common configuration items, seems like a good arrangement. For now, ad-hoc and messy will work here.

**Comment by BentonEdmondson** [comment]
I you're on NixOS, I recommend against using the binary; try installing it through NixOS. `nix profile install github:BentonEdmondson/knock` should work. Then try `knock -v` to verify you have the right version.

**Comment by tlavoie** [comment]
Thanks Benton. I ended up going back to an Arch-based distro on my main
system, with the idea of easing into some Nix concepts somewhat more
gradually.

So, I'm using the binary bundle for now, and it is working fine.
Thanks for your help!

**Comment by BentonEdmondson** [comment]
@tlavoie sounds good. Glad it's working. Yes NixOS as a daily driver is often quite a pain
