### ISSUE TITLE
Debian 11, Archive.org EPUB, libX11 error

### ISSUE THREAD

**Issue by historical-theology** [BentonEdmondson/knock#26]
I am new to knock, so please let me know what I am missing. Thank you for your hard work on this project.

Up-to-date Debian 11 Stable with spectrwm (no other DE or WM). 
libX11-6 is (of course) installed.

Adobe EPUB loan from from Archive.org.

Error message:

```
corey@corey-debian~/Downloads> ./knock URLLink.acsm
./nix/store/j0rfffzsih095w4nvl6cp0zbmdiaycfs-nix-user-chroot-2c52b5f/bin/nix-user-chroot: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
```

**Comment by pide2000** [comment]
I just created a docker image to run knock without relying on os deps. 
Maybe this helps: https://github.com/pide2000/containerized-knock

**Comment by historical-theology** [comment]
> I just created a docker image to run knock without relying on os deps. Maybe this helps: https://github.com/pide2000/containerized-knock

Thank you for sharing. That looks helpful. It is not, however, a solution to what seems to be an underlying problem with the utility itself. A CLI tool like knock ought to be neutral with regard to Unix-like OS -- or at least with regard to whatever GNU/Linux distribution one should use (especially among the major distros).

In fact, I just tried to install knock in up-to-date Manjaro (also with spectrwm) rather than Debian 11 Stable to see if it might be tied to Debian or perhaps to using some out-of-date libX11 library, but I receive the exact same error message.

After re-reading knock's documentation, I think that the issue in the error message is actually something to do with its 'nix bundle' packaging.

@BentonEdmondson , what do you make of all this?

Thank you again, folks.

**Comment by pide2000** [comment]
Your problem is well documented in 
https://github.com/BentonEdmondson/knock#setup-and-installation 
point e) 
> If you receive an error that says something like ./nix/store/...: not found or **./nix/store/...: No such file or directory** then you might not have user namespaces enabled. Try running the following to fix it: ......

I recommend you to read about namespaces and why they are anebled in your os before disabling them.

**Comment by historical-theology** [comment]
> Your problem is well documented in https://github.com/BentonEdmondson/knock#setup-and-installation point e)
> 
> > If you receive an error that says something like ./nix/store/...: not found or **./nix/store/...: No such file or directory** then you might not have user namespaces enabled. Try running the following to fix it: ......
> 
> I recommend you to read about namespaces and why they are anebled in your os before disabling them.

Thank you. You see, I followed the directions and enabled user namespaces in systemd, both in Manjaro and Debian temporarily with 'sudo systemctl -w kernel.unprivileged_userns_clone=1'. I receive the same error message in both places. I thought that this error message was something new, but if it is indeed a user namespace message...

Do user namespaces need to be enabled before marking 'knock' as executable in the first place or some strange thing? I cannot imagine that would be the case.

**Comment by pide2000** [comment]
I've tested this on a headless Debian 10 and it just works. No Debian 11 available at the Moment. 
I don't know what the problem causes then. Sry

**Comment by BentonEdmondson** [comment]
@historical-theology try release `1.2.0`. No need to worry about any user namespaces stuff for that release. It should just work.

**Comment by BentonEdmondson** [comment]
I'm certain this will work on `1.2.0`. If not feel free to reopen
