### ISSUE TITLE
Provide latest build on generic url and docker container 

### ISSUE THREAD

**Issue by pide2000** [BentonEdmondson/knock#27]
Hi, 
is it possible to provide the latest build on a generic url?  
I've written a little docker container to do the boring stuff. I'll do a pull request, but for now, the path to the latest build is hardcoded to  .../0.1.0-alpha/knock-0.1.0-alpha-x86_64-linux because of that, for every new build one has to correct the path to the latest build path.
My suggestion will be to use .../latest/knock-latest-x86_64-linux or something like this. 

The reason why I've created a Docker container is the following: You  recommend to do
`$: echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf
$: sudo reboot`
this is a security issue and I don't want to set and unset it every time using knock. 

Kind regards

**Comment by BentonEdmondson** [comment]
I'll think about making the binaries a consistent name (I'd probably choose `knock-x86_64-linux`). Here's an SO thread discussing workarounds: https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo.

**Comment by BentonEdmondson** [comment]
Also, it looks like I completely forgot to respond to this when I first responded to this issue, but I'm pretty sure Nix has pretty good Docker support. I'll look into this on next release.

**Comment by BentonEdmondson** [comment]
I'm planning on an update tomorrow that will be released via Docker container.

**Comment by BentonEdmondson** [comment]
The latest release (`1.2.0`) doesn't require any particular user namespaces kernel setting so this is not an issue anymore. It is a completely static binary with no dependencies, so docker does essentially nothing for it.
