### ISSUE TITLE
Support PDFs

### ISSUE THREAD

**Issue by noideawhatiamtalkingabout** [BentonEdmondson/knock#3]
from my purchase i got a .aacsm file - and .knock left a .drm.epub file

`file -b s2.drm.epu`b
PDF document, version 1.4

and i cannot open it - as it requires a password

any idea/short time workaround?

**Comment by noideawhatiamtalkingabout** [comment]
creation history:

`./knock /home/u/Downloads/ss.acsm`

This device is not registered with Adobe.
Enter your Adobe account's email address: xxx@xxx.com
Enter your Adobe account's password:
Registering this device with Adobe...
Downloading the ACSM file from Adobe...
Decrypting the file...
Traceback (most recent call last):
File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 429, in
sys.exit(cli_main())
File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 423, in cli_main
result = decryptBook(userkey, inpath, outpath)
File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 337, in decryptBook
with closing(ZipFile(open(inpath, 'rb'))) as inf:
File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/zipfile.py", line 1269, in init
self._RealGetContents()
File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/zipfile.py", line 1336, in _RealGetContents
raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Traceback (most recent call last):
File "/nix/store/f6m60ymgfh2clcqc3fz5s7kqla4c23xv-knock-0.0.0/bin/.knock-wrapped", line 50, in
subprocess.check_output([
File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/subprocess.py", line 415, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['inept-epub', '/home/u/.config/knock/activation.xml', '/home/u/Downloads/ss.drm.epub', '/home/u/Downloads/ss.epub']' returned non-zero exit status 1.

**Comment by BentonEdmondson** [comment]
In the meantime try renaming it to `s2.pdf` and sending it through Calibre. I will look into adding PDF support.

**Comment by noideawhatiamtalkingabout** [comment]
kindly explain what you mean with "send it through calibre" ?

oc this was the first thing I did - i renamed it to .pdf and in calibre i said `add book`, so I added it - but i cannot view it as it requires a password as I had already mentioned above....

**Comment by BentonEdmondson** [comment]
That's what I meant. I will work on getting PDFs supported

**Comment by BentonEdmondson** [comment]
@noideawhatiamtalkingabout please email me at bentonedmondson at gmail com

**Comment by BentonEdmondson** [comment]
It looks like it is too new a PDF. This only works on Adobe Digital Editions 2.0.1 content and I think yours is v4.

```
{
  'Filter': /EBX#5fHANDLER,
  'EBX_TITLE': b'',
  'ADEPT_ID': b'urn:uuid:2f58333c-eb80-4c2c-be5f-68eb516778f4',
  'V': 4,
  'EBX_AUTHOR': b'',
  'Length': 128
}
```

Can you check the version that your ACSM file is?

**Comment by noideawhatiamtalkingabout** [comment]
>>Can you check the version that your ACSM file is? 
@BentonEdmondson how?

**Comment by BentonEdmondson** [comment]
The place where you got the ACSM file from probably had a notice like "this file requires Adobe Digital Editions version x.x.x to view". Besides that I don't know how to check the version.

**Comment by BentonEdmondson** [comment]
Looks like libgourou might not support PDFs: http://indefero.soutade.fr/p/libgourou/issues/17/. I guess the Adobe server sends the content over, and then the client has to still add additional metadata to the file, which libgourou is not doing

**Comment by BentonEdmondson** [comment]
According to https://github.com/apprenticeharper/DeDRM_tools/issues/1780#issuecomment-887771399 the Adept client must add in a certain field that it is not adding, so to get PDF support for Knock we need libgourou PDF support  (see http://indefero.soutade.fr/p/libgourou/issues/17/). I don't think this will happen soon

**Comment by BentonEdmondson** [comment]
It looks like libgourou now supports PDFs so I will reopen this

**Comment by BentonEdmondson** [comment]
If anyone has a fresh ACSM/PDF file, please send it to me for testing. I preferably need an ACSM file that hasn't been run through knock yet.

cc: @sp8996 @noideawhatiamtalkingabout

**Comment by dmty** [comment]
Hi @BentonEdmondson, hope this helps. Should live for another 10 days. 
[chemistry.acsm.zip](https://github.com/BentonEdmondson/knock/files/7158140/chemistry.acsm.zip)

**Comment by sp8996** [comment]
@BentonEdmondson 
[black-horn.acsm.zip](https://github.com/BentonEdmondson/knock/files/7158583/black-horn.acsm.zip)

**Comment by LennyPenny** [comment]
@BentonEdmondson you can borrow lots of scanned books for free @ archive.org and then download PDF acsms for testing

**Comment by BentonEdmondson** [comment]
@LennyPenny thank for the suggestion. Are you saying the ACSM files are on archive.org? I've looked at some of the books and they provide many formats but I haven't found ACSM. For instance [this one](https://archive.org/details/indiantribesofun02scho) shows these options for download.
![image](https://user-images.githubusercontent.com/55590329/140663881-40141280-865c-430c-91a7-30da9cb186aa.png)

**Comment by dmty** [comment]
@BentonEdmondson you need to go to [Books to borrow](https://archive.org/details/inlibrary?and[]=lending___status%3A%22available_to_borrow%22) and select the ones that allow borrowing for 14 days then it will give you the option to download ACSM file.

**Comment by LennyPenny** [comment]
dmty is right, here is an example book you can borrow with a pdf ACSM download https://archive.org/details/bookofoldmaps0000unse

**Comment by BentonEdmondson** [comment]
Added in latest release
