### ISSUE TITLE
Unworking workaround

### ISSUE THREAD

**Issue by TLabsPeter** [BentonEdmondson/knock#31]
I have the following error messages:
` ./URLLink.acsm: line: 1: fulfillmentToken: No such file or directory `
`./URLLink.acsm: line: 2: syntax error „newline” near unexpected token`
`./URLLink.acsm: line: 2: `  <distributor>urn:uuid:d051ad0d-03ed-4b63-b257-5bfe2e304a80</distributor>`

I tried to run, the following line as the wiki sais:
`echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf   `
But it got me the following error message, even with sudo:
`zsh: permission denied: /etc/sysctl.conf `

I'm using the latest manjaro with plasma desktop today (2021.12.06)

**Comment by zd4y** [comment]
try `sudo bash -c 'echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf'`

**Comment by TLabsPeter** [comment]
Thanks! It worked.
