### ISSUE TITLE
RMSDK source

### ISSUE THREAD

**Issue by JJTech0130** [BentonEdmondson/knock#32]
I don't know if this is at all helpful for you, but during my research I found this: http://fusionspec.com/bn/Adobe_RMSDK_9_0_BN.zip
Perhaps you could use it as a basis for more features? (I'm not sure what the SDK supports, could you get anonymous activations?!)

**Comment by BentonEdmondson** [comment]
@JJTech0130 I assume you want me to delete this? I can

**Comment by JJTech0130** [comment]
Yes, please.
