### ISSUE TITLE
Adobe Account Deactivation?

### ISSUE THREAD

**Issue by Linux-Geezer** [BentonEdmondson/knock#33]
Not an issue but a question. I don't see any other place to ask questions, so I'm using the Issues feature.

This app has been available for a short period of time, but has anyone had their Adobe account deactivated because Adobe detected the app as something other than Adobe Digital Editions?

**Comment by fluxus-collab** [comment]
Hi,
For the moment, my account is still working.

**Comment by BentonEdmondson** [comment]
Closing this. Feel free to continue discussion right here though. If anyone's account does get deactivated please reopen.
