### ISSUE TITLE
How do you de-activate the device?

### ISSUE THREAD

**Issue by jkinross** [BentonEdmondson/knock#34]

**Comment by Leseratte10** [comment]
It is not possible to de-activate a device, not even with ADE itself. All that does is delete the activation information, it doesn't restore one of the six available activations. 

To do that, just delete the activation.xml, device.xml and devicesalt files.

**Comment by BentonEdmondson** [comment]
Thanks @Leseratte10, for more info on where those files are located see https://github.com/BentonEdmondson/knock/issues/14#issuecomment-925930638
