### ISSUE TITLE
Cannot handle spaces in the password

### ISSUE THREAD

**Issue by salvipeter** [BentonEdmondson/knock#36]
Originally I had a space in my password. Then the output was:
```
Enter password for <***@yahoo.com> :                                                             
Exception code : 0x1003                                                                             
Message        : E_AUTH_FAILED http://adeactivate.adobe.com/adept/SignInDirect ***@yahoo.com CUS05051     
```
It worked after changing my password to one without spaces. I guess the problem must be with quoting the arguments to `adept_activate`.

**Comment by BentonEdmondson** [comment]
As of release `1.2.0` there is no logging in (logins are anonymous) so this is no longer an issue.
