### ISSUE TITLE
Issues with special characters in passwords

### ISSUE THREAD

**Issue by chpoit** [BentonEdmondson/knock#38]
When using passwords with special characters the authentication fails. From a quick look at the code, my guess is that it fails when the `stding.encode()` in `lib/utils.py` is called. 

This guess comes from hardcoding my **old, now changed,** password `cY5UqUpGdRa#2!f4!ELrmvMO` in the code and still having it fail.

I left the password in in case you want to experiment

This is the error I had:
```
knock> adept_activate -u EMAIL -O /home/chpoit/.config/knock/acsm

Enter password for <EMAIL> : 
Exception code : 0x1003
Message        : E_AUTH_FAILED http://adeactivate.adobe.com/adept/SignInDirect EMAIL CUS05051


knock[1]>
```

**Comment by Aculeo** [comment]
I'm getting this error even without any special characters (simply alphanumeric).

**Comment by whowantsmybigdata** [comment]
> I'm getting this error even without any special characters (simply alphanumeric).

I had the same kind of error and the solution was, I needed to shorten my password. I didn't try if it can have special characters as I removed them before to try if thats the solution but I had a 32 digit password and the error appeared and with a 10 digit one it was working normally!

**Comment by wanageeska** [comment]
Just wanted to provide a recent experience on the issue: authentication failed for me with 12 alphanum chars but worked with 8 of them. I only tested 12 and 8 and nothing in-between.

**Comment by BentonEdmondson** [comment]
As of release `1.2.0` there are no more logins, so this is fixed.
