### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by Nebula-0-System** [BentonEdmondson/knock#4]
hi, i was planning to donate to this project and don't see any paypal, ko-fi, etc links. please consider adding them because while this tool is niche, it's worked flawlessly for me and i wanna support those contributing.

**Comment by BentonEdmondson** [comment]
The vast majority of the difficulty of this project is implemented in the [libgourou](https://forge.soutade.fr/soutade/libgourou) library by Grégory Soutadé. Please donate to him if you want to support the project. After briefly looking I didn't see a way to donate to him but you can ask on the [libgourou issue tracker](https://forge.soutade.fr/soutade/libgourou/issues).

**Comment by BentonEdmondson** [comment]
Also if you do find a way to donate to him please reply here so I can add it to the readme.

**Comment by alvilag** [comment]
Unfortunately, the confirmation email to register to that website never arrives, so I cannot contact him. I tried with two different email addresses, and to login via github...

Thanks in any case.

**Comment by bwitt** [comment]
> Unfortunately, the confirmation email to register to that website never arrives, so I cannot contact him. I tried with two different email addresses, and to login via github...

mine went to spam.  I've opened https://forge.soutade.fr/soutade/libgourou/issues/6

**Comment by alvilag** [comment]
Thanks! I see he created a paypal link, I'll make a donation there.
