### ISSUE TITLE
New issue?

### ISSUE THREAD

**Issue by GitN3wb** [BentonEdmondson/knock#41]
I am on Pop!_OS 21.10 and I get this issue:

> Error: Invalid value for 'PATH': File '/media/popadmin/EHDD1_Linux/My_Book-pdf.acsm' does not exist.

I tried the proposed command just in case:
`echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf`
but to no avail.

**Comment by kgagnon** [comment]
reboot for quick and easy systemctl restart

**Comment by BentonEdmondson** [comment]
@GitN3wb try out release `1.2.0`

**Comment by BentonEdmondson** [comment]
I'm certain `1.2.0` fixes this. Reopen if not
