### ISSUE TITLE
"This device is not registered with Adobe. Enter your Adobe account's email address: "

### ISSUE THREAD

**Issue by miaocrosoft** [BentonEdmondson/knock#43]
I followed the set-up and installation instructions as described on `README.md`. I installed the release dated 4 December 2021.

After running `./knock /home/miao/Downloads/urllink.acsm`, I see the following message:

``
Received an ACSM (Adobe) file...
This device is not registered with Adobe. 
Enter your Adobe account's email address: 
``

![image](https://user-images.githubusercontent.com/87876601/148678763-e74a96a4-8ec9-4db1-8538-ed2a3c597660.png)

My operating system is Manjaro Qonos 21.2.0. Please advise.

**Comment by AndyJWard** [comment]
I have exactly the same issue ...
Received an ACSM (Adobe) file...
This device is not registered with Adobe.
Enter your Adobe account's email address: 

I've no idea how to proceed, I know Adobe Digital Editions was/isn't available on linux so I'm stumped.
I'm running Kubuntu 20.04
Thanks ... Andy

**Comment by BentonEdmondson** [comment]
I don't understand the problem. It's prompting you to enter your Adobe account's email address. This is necessary to remove DRM. Once you enter it and the password the script will continue.

**Comment by AndyJWard** [comment]
Ah, OK, my understanding is even less than I realised.  I've downloaded from Kobo the acsm of a book I have and am trying to read on my PC.  I guess I'll try my kobo account email address.  Thanks for responding, sorry if I'm wasting your time.  Andy

**Comment by kgagnon** [comment]
you need an Adobe account. Has nothing to do with your kobo account.

**Comment by AndyJWard** [comment]
Thanks Kevin, I got there eventually - also found that the acsm downloaded has an expiration period and had to re-download.
Andy

**Comment by BentonEdmondson** [comment]
@miaocrosoft hopefully entering your Adobe email and password worked. If not feel free to reopen

**Comment by BentonEdmondson** [comment]
For the record, as of `1.2.0`, email login is no longer required
