### ISSUE TITLE
Question: Why the \n on password input?

### ISSUE THREAD

**Issue by kgagnon** [BentonEdmondson/knock#44]
https://github.com/BentonEdmondson/knock/blob/8fd6244db8b895d96ae1d6da5aaea4c2eb0f48ff/lib/handle_acsm.py#L31

**Comment by BentonEdmondson** [comment]
It's passing the password to libgourou, which is cpp and uses something like `std::cin >> password` to read in the password. `std::cin` delimits on whitespace so `\n` signifies the end of the password
