### ISSUE TITLE
Nothing happens when I run ./knock

### ISSUE THREAD

**Issue by 610th** [BentonEdmondson/knock#46]
I followed the non-NixOS instructions (1.1.0-alpha), but when I run the command `./knock` nothing happens. Just silence. Does not matter what kind of arguments I provide.

I'm using Pop!_OS 20.04.

**Comment by stevek-pro** [comment]
Same here. It is just doing absolutely nothing, except creating a json file in a folder called knockpy. Is this project still maintained?

**Comment by carygravel** [comment]
It took a while on my machine the first time. How long did you give it?

**Comment by BentonEdmondson** [comment]
@610th try release `1.2.0` and tell me what happens
