### ISSUE TITLE
Raspberry Pi support

### ISSUE THREAD

**Issue by Suniron** [BentonEdmondson/knock#48]
Hey there,

My machine is a Raspberry Pi 4 4GB with Raspbian 64bits (Debian based)

I followed the steps is readme to install knock.

When i run kock with this command (i tried also without sudo):

```
sudo ./knock /home/admin/divers/mybook.acsm
```

And i got the error bellow:

```
./nix/store/ml4m2016xm278m8h4w1x3gaayq9kh3p2-startup: 2: ./nix/store/ml4m2016xm278m8h4w1x3gaayq9kh3p2-startup: ./nix/store/j0rfffzsih095w4nvl6cp0zbmdiaycfs-nix-user-chroot-2c52b5f/bin/nix-user-chroot: Exec format error
```

Anyone can help me ?

**Comment by lpil** [comment]
I wager this is due to the Nix config being amd64 based while the Raspberry PI is aarch64 based

**Comment by BentonEdmondson** [comment]
@Suniron Raspberry Pis are ARM devices and this software is designed for x86_64. So this software cannot currently run on Raspberry Pis. I'll look into supporting other architectures

**Comment by BentonEdmondson** [comment]
Planning to support RPis (Linux aarch64) and maybe even x86_64 and aarch64 Macs very soon

**Comment by BentonEdmondson** [comment]
I won't have access to a Pi for about another week and a half. But once I do I think this'll be out relatively quick

**Comment by Fabbi** [comment]
aarch64 should be working with #60 . For something like Arm7vl you'd probably have to add the architecture entry and try what happens. 
installing `nix` on rpi doesn't seem to be that straightforward, otherwise I'd try that out on mine.

**Comment by BentonEdmondson** [comment]
Added in [release 1.3.1](https://github.com/BentonEdmondson/knock/releases/tag/1.3.1)
