### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by jmehne** [BentonEdmondson/knock#5]
Hi there,

when trying to run knock, it fails with:

```
./knock path/to/my.acsm 
/tmp/tmpx-2c06c77c82240f03/dat/../run: line 1: ./nix/store/plhgfmrzicfphpfl501nrnkmpyprzkzd-startup: No such file or directory
```

This is on Arch Linux with the initial release binary.

**Comment by BentonEdmondson** [comment]
Try the new release and make sure you have user namespaces enabled in your kernel (`CAP_SYS_USER_NS`)

**Comment by rkoshak** [comment]
I see the exact same error. I downloaded the latest release (knock-0.0.1-alpha-x86_64-linux) and `CONFIG_USER_NS=y`.

Ubuntu 20.04.2 LTS running on an ESXi VM

**Comment by BentonEdmondson** [comment]
Assuming you are on a 64-bit machine I don't know. I will notify you when I get an AppImage bundled. I doubt that will be very soon though

**Comment by rkoshak** [comment]
Yes, it's 64-bit

**Comment by jmehne** [comment]
Thanks, i don't get the error anymore with the 0.0.1 release.

**Comment by rkoshak** [comment]
I did some playing around and I was hasty when I said it was the exact same error. Though I suspect waiting for the AppImage is still going to be the solution. I tested out the 0.0.0 version just to see if it ran differently and it did in fact run, at least until encountering an error:

0.0.0 run
```
rich@argus:~ 👁️  ./knock-0.0.0-alpha-x86_64-linux ~/The_City_and_the_Stars-epub.acsm 
This device is not registered with Adobe.
Enter your Adobe account's email address: <my adobe login email>
Enter your Adobe account's password: 
Registering this device with Adobe...
Downloading the ACSM file from Adobe...
Decrypting the file...
Traceback (most recent call last):
  File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 429, in <module>
    sys.exit(cli_main())
  File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 423, in cli_main
    result = decryptBook(userkey, inpath, outpath)
  File "/nix/store/zpjmnj7d18h6y1ylx541fb0abj9f4gb7-inept-epub-7.0/bin/inept-epub", line 337, in decryptBook
    with closing(ZipFile(open(inpath, 'rb'))) as inf:
FileNotFoundError: [Errno 2] No such file or directory: '/home/rich/The_City_and_the_Stars-epub.drm.epub'
Traceback (most recent call last):
  File "/nix/store/f6m60ymgfh2clcqc3fz5s7kqla4c23xv-knock-0.0.0/bin/.knock-wrapped", line 50, in <module>
    subprocess.check_output([
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/nix/store/6cfajs6lsy9b4wxp3jvyyl1g5x2pjmpr-python3-3.8.9/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['inept-epub', '/home/rich/.config/knock/activation.xml', '/home/rich/The_City_and_the_Stars-epub.drm.epub', '/home/rich/The_City_and_the_Stars-epub.epub']' returned non-zero exit status 1.
```
That looks promising. It at least got to the point of asking for my credentials.

However when I run the 0.0.1 release I get

```
rich@argus:~ 👁️  ./knock-0.0.1-alpha-x86_64-linux ~/The_City_and_the_Stars-epub.acsm
./nix/store/7ighrasw2nr0na0b5z4vwmn6llkq8y0n-startup: 2: ./nix/store/j0rfffzsih095w4nvl6cp0zbmdiaycfs-nix-user-chroot-2c52b5f/bin/nix-user-chroot: not found
```

Hope this helps.

I can open a new issue if that works best for you.

**Comment by BentonEdmondson** [comment]
Your issue with 0.0.0 is that the file received from Adobe isn't an EPUB (Knock only supports EPUBs, https://github.com/BentonEdmondson/knock/issues/3).

0.0.1 makes the error nicer. Your issue with 0.0.1 must be a problem with `nix bundle`. They say

> Requires Linux kernel with CAP_SYS_USER_NS on and permissions setup correctly

That's all I can see being a problem. @jmehne did you change anything on your system when you went from 0.0.0 to 0.0.1?

**Comment by rkoshak** [comment]
That acsm file is definitely for the epub. It has "epub" in the name (the PDF version has "pdf" in the name) and when I opened the file in ADE itself it downloaded the epub version of the book.

`CAP_SYS_USER_NS` is set to `y`.

```
rich@argus:~ 👁️  grep CONFIG_USER_NS /boot/config-*
/boot/config-5.4.0-80-generic:CONFIG_USER_NS=y
``` 

I'm not sure what permissions need to be set correctly. I get the same error when I run it as root. The acsm file is owned by my user with read permissions for all. I'm running docker containers on this machine (which I believe uses namespaces too) in case that's relevant or informative. But if the 0.0.0 version runs far enough to at least download the file would that still be the problem? Or are there changes in 0.0.1 that use namespaces in a different way?

But just in case I ran `sudo sysctl -w kernel.unprivileged_userns_clone=1` based on some searching around but get the same error. I can't find what other permissions I might need to configure.

**Comment by BentonEdmondson** [comment]
According to [this](https://unix.stackexchange.com/a/602409/482807) you might need to run `echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf` and reboot.

Regarding the EPUB, run 0.0.0 and you should end up with `The_City_and_the_Stars-epub.drm.epub`. Run `file -b The_City_and_the_Stars-epub.drm.epu` and send over the results.

**Comment by rkoshak** [comment]
Results from the `file` command:

```
rich@argus:~ 👁️  file -b The_City_and_the_Stars-epub.drm.epub 
cannot open `The_City_and_the_Stars-epub.drm.epub' (No such file or directory)
```
On a lark I did a find on the whole file system and that files does not exist at all. I suppose that means it failed to download at all?

As for the 0.0.1 version, setting the parameter in sysctl.conf and rebooting seemed to do the trick. I wanted to test whether it made a difference without making the change permanent so I didn't add it to the conf. And based on that link it should have worked for the current session just by running the sysctl command like I did. And it seems like it should have worked even without that setting when I ran it as root. So I wonder if there was something else going on and the reboot cleared it out. 

In any case, it appears to have successfully worked after the reboot. 

```
rich@argus:~ 👁️  ./knock-0.0.1-alpha-x86_64-linux ~/The_City_and_the_Stars-epub.acsm
Downloading the EPUB file from Adobe...
Decrypting the file...

DRM-free EPUB file created:
/home/rich/The_City_and_the_Stars-epub.epub
```

And I was able to open it without problem. 

I can't say whether the problem was that setting or that I just needed to reboot but all appears to be working well. The only thing that would be better would be an arm build and/or more direct integration with Calibre. 

Keep up the good work and thanks for the help!

**Comment by BentonEdmondson** [comment]
Awesome!! This is great news! I will add this to the readme when I get a chance!

**Comment by BentonEdmondson** [comment]
@jmehne @rkoshak can you guys share where you got the your ACSM files for so I can add to the readme that those sources are verified to work? Thanks. If you don't want to, that's no problem

**Comment by rkoshak** [comment]
I get all my DRM'd ascm files from Google Books.

**Comment by jmehne** [comment]
Probably not particularly relevant for international audiences - a largish German bookstore: hugendubel.de

**Comment by BentonEdmondson** [comment]
Thanks guys

**Comment by onodera-punpun** [comment]
I'm experiencing this issue on the most recent release. I did the `kernel.unprivileged_userns_clone=1` trick. On the older release (`0.1.0`) it works fine however.
