### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by borisrorsvort** [BentonEdmondson/knock#53]
Tried on the latest osx: 

`./nix/store/ml4m2016xm278m8h4w1x3gaayq9kh3p2-startup: line 2: ./nix/store/j0rfffzsih095w4nvl6cp0zbmdiaycfs-nix-user-chroot-2c52b5f/bin/nix-user-chroot: cannot execute binary file`

**Comment by BentonEdmondson** [comment]
@borisrorsvort try release `1.2.0` and tell me what happens

**Comment by BentonEdmondson** [comment]
Certain this is resolved on `1.2.0`, reopen if not
