### ISSUE TITLE
unshare(): Invalid argument

### ISSUE THREAD

**Issue by hashblen** [BentonEdmondson/knock#55]
Trying to convert an acsm I downloaded from google books, to PDF specifically.
But when I first launched, it took a while, then it said `unshare(): Invalid argument`.
Running it again still shows this.
I am on Ubuntu 20.04 LTS

**Comment by BentonEdmondson** [comment]
@hashblen try release `1.2.0` and tell me what happens

**Comment by hashblen** [comment]
Ok, it seems to work perfectly now. Thanks a lot for this project!
