### ISSUE TITLE
Lacking portability

### ISSUE THREAD

**Issue by casey2069** [BentonEdmondson/knock#56]
Error with yash linked to sh:
`% sudo rm /usr/bin/sh`
`% sudo ln -s /usr/bin/yash /usr/bin/sh`
`% knock /home/me/URLLink.acsm`
`/bin/sh: cannot read input: Invalid or incomplete multibyte or wide character`
`/home/me/.local/bin/knock:89: syntax error: the here-document content is not closed by '+'`
 `/bin/sh: cannot read input: Invalid or incomplete multibyte or wide character`
`/home/me/.local/bin/knock:89: syntax error: ')' is missing`
`/home/me/.local/bin/knock:89: syntax error: '}' is missing`

Error with mrsh linked to sh:
`% sudo rm /usr/bin/sh`
`% sudo ln -s /usr/bin/mrsh /usr/bin/sh`
`% knock /home/me/URLLink.acsm`
`sh: ../mrsh/parser/word.c:337: expect_word_command: Assertion 'symbol(parser, TOKEN)' failed.`
`[1]    285634 IOT instruction (core dumped)  knock /home/me/URLLink.acsm`

knock is working with bash, dash and zsh as intended.

**Comment by BentonEdmondson** [comment]
@casey2069, try release `1.2.0` on yash and tell me what happens.

**Comment by casey2069** [comment]
yash
`ls -l /usr/bin/sh`
`lrwxrwxrwx 1 root root 13 Jun  5 12:23 /usr/bin/sh -> /usr/bin/yash`
Proving version
`% md5sum ~/.local/bin/knock`
`7dd4b47e9f362fd918f70bfda590b45d  /home/me/.local/bin/knock`
**Shown working**
`% knock ./URLLink.acsm`
`downloading the file from Adobe...`
`Download 100%`
`removing DRM from the file...`
`DRM-free PDF file generated at ./URLLink.pdf`
Works with mrsh as well. 1.2.0 seems to have fixed this issue.

**Comment by BentonEdmondson** [comment]
Epic!
