### ISSUE TITLE
Thank you! This worked perfectly.

### ISSUE THREAD

**Issue by nefertari22** [BentonEdmondson/knock#6]
This was exactly what I needed. I wasn't sure how to "install" it, but after following your instructions in the "How to Use Binary Release" issue thread, my acsm file is now a usable epub. Perhaps you could incorporate those instructions for use into the read me? 

Also, I love that you named it after a D&D spell. Thanks again!

**Comment by Jubjub** [comment]
Yes, I've been waiting for a program that could do this for a long time, can't believe I just randomly checked today and you created a brand new tool that works perfectly recently. 

Just one little thing, the tool needs the absolute path and doesn't work with a relative path which confused me a little bit at first.

**Comment by BentonEdmondson** [comment]
Guys this is great. I'm glad it is working well. @nefertari22 I will add them to the readme

@Jubjub ah I didn't realize that. I will develop a fix. I opened https://github.com/BentonEdmondson/knock/issues/7

**Comment by BentonEdmondson** [comment]
@nefertari22 @Jubjub can you guys share where you got your ACSM files from so I can them to the list of verified ACSM sources in the readme? Thanks. If you don't want to that's no problem

**Comment by nefertari22** [comment]
I've been able to decrypt acsm files from the Adobe sample ebook library and from Kobo.com (though most new ones are provided as epub already from there). A couple of other sources have been successful as well.

**Comment by BentonEdmondson** [comment]
Thanks

**Comment by Yannnd** [comment]
> @nefertari22 @Jubjub can you guys share where you got your ACSM files from so I can them to the list of verified ACSM sources in the readme? Thanks. If you don't want to that's no problem

Thanks SO MUCH for this sublime piece of Python art! Finally, finally, something that **just works great**, in contrary to the Wine and VM solutions found everywhere, which have very limited reliability and reproducability.

I can confirm that ebooks in *.acsm format, borrowed from from the Dutch public library (https://www.onlinebibliotheek.nl) are converted to *.epub perfectly with my ADE credentials. Wonderful!

**Comment by BentonEdmondson** [comment]
Awesome! I'm glad it is working well for you. I'll reopen this to remind myself to add that to the readme

**Comment by zd4y** [comment]
Thank you! I can confirm books borrowed from overdrive are working, specifically https://comfama.overdrive.com/
