### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by maximilliangeorge** [BentonEdmondson/knock#6]
Hi, this looks like an awesome way to actually, like, _read_ the books you've paid for without having to jump through arbitrary hoops set up by the failing monolith Adobe.

I noticed you removed macOS from the releases (explicitly mentioned in a git message), I'm wondering if it's on the roadmap?

**Comment by BentonEdmondson** [comment]
I would be willing to take a patch if someone submitted one, but I don't have a Mac so couldn't develop it myself. There was a PR on this repo to support Mac before I deleted the repo which I think worked and which you may be able to find on the Wayback Machine.
