### ISSUE TITLE
Handle relative paths

### ISSUE THREAD

**Issue by BentonEdmondson** [BentonEdmondson/knock#7]
https://github.com/BentonEdmondson/knock/issues/6#issuecomment-890008150

**Comment by BentonEdmondson** [comment]
Fixed by https://github.com/BentonEdmondson/knock/commit/868597396cd78d2bcef5a49645f9ab0b951de088

**Comment by martinrebane** [comment]
Hi! Thank you for a great work! Just wanted to mention that I downloaded knock 0.1.0 which should fix relative paths. However, having both knock and .acsm file in the same folder, relative paths did not work for a plain file name:
```
martin@host:~/Downloads$ ./knock URLLink.acsm 
ERROR: /URLLink.acsm does not exist.
```
Full path worked well, so not a big problem :)
I was using Ubuntu 20.04.

**Comment by BentonEdmondson** [comment]
Thanks for opening this. I'll look into it when I get a chance; no time soon though as school's starting back up

**Comment by BentonEdmondson** [comment]
I'm realizing the shell should be taking care of all this expansion (e.g. `./{one,two}.acsm`) so I'll have to figure out why it isn't and I'm having to fix it in the script

**Comment by BentonEdmondson** [comment]
Fixed in latest release
