### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by alvilag** [BentonEdmondson/knock#7]
Hello,

Fantastic project. I cannot find a way to contribute financially to your work. If you set one up, I'd be happy to donate a small sum, and I'm sure I'm not the only one--removing DRMs via ADE and Wine really is a pain.

Thanks in any case for your work!

Best,
A.

**Comment by BentonEdmondson** [comment]
Hello. Glad you find the tool helpful. See https://github.com/BentonEdmondson/knock/issues/4 for info on donating.
