### ISSUE TITLE
Creates .drm file but then crashes

### ISSUE THREAD

**Issue by jezgillen** [BentonEdmondson/knock#8]
Hi, thanks for the effort put into this software. I might have done something wrong, because I installed it using "nix build", which I haven't used before. The program creates a .drm file but then crashes with the following output. Any advice?
I'm on Ubuntu 20.04

Downloading the EPUB file from Adobe...
Decrypting the file...
ERROR: 
CompletedProcess(args=['inept-epub', '/home/jeremy/.config/knock/activation.xml', '/home/jeremy/Music/URLLink.drm', '/home/jeremy/Music/URLLink.epub'], returncode=1, stdout=b'', stderr=b'Traceback (most recent call last):\n  File "/nix/store/d4c9q610gg5fkrvzdkks3nfrm0xymxrn-inept-epub-7.0/bin/inept-epub", line 271, in <module>\n    AES, RSA = _load_crypto()\n  File "/nix/store/d4c9q610gg5fkrvzdkks3nfrm0xymxrn-inept-epub-7.0/bin/inept-epub", line 265, in _load_crypto\n    AES, RSA = loader()\n  File "/nix/store/d4c9q610gg5fkrvzdkks3nfrm0xymxrn-inept-epub-7.0/bin/inept-epub", line 64, in _load_crypto_libcrypto\n    libcrypto = CDLL(libcrypto)\n  File "/nix/store/yqjhkdarf7p74wcha7aypzsb751n7wl2-python3-3.9.5/lib/python3.9/ctypes/__init__.py", line 374, in __init__\n    self._handle = _dlopen(self._name, mode)\nOSError: libcrypto.so.1.1: cannot open shared object file: No such file or directory\n')

**Comment by BentonEdmondson** [comment]
Try `nix shell github:BentonEdmondson/knock` and then `knock ~/...`

**Comment by BentonEdmondson** [comment]
@jezgillen working?

**Comment by jezgillen** [comment]
Nah sorry, thanks for the help, but I got busy and didn't have time to mess around with it much. The same error seemed to be coming up, so I think I probably just missed an installation step. I'll close the issue and get back to it when I have time.
